services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: panel_admin
        working_dir: /var/www/html
        environment:
            APP_ENV: production
            APP_DEBUG: 'false'
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html:ro
            - ./compose/nginx/:/etc/nginx/conf.d/:ro
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: qvluAJN69aEzsxm
            MYSQL_DATABASE: AdminPanel
            MYSQL_USER: panelAdmin
            MYSQL_PASSWORD: 169aE3zs6vluAJN
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - app-network

volumes:
    dbdata:
        driver: local

networks:
    app-network:
        driver: bridge
